### ISSUE TITLE
Where are the recurring events?

### ISSUE THREAD

**Issue by saltybeagle** [unl/UNL_UCBCN_Frontend#12]
Are recurring events appearing correctly?

**Comment by mfairchild365** [comment]
There is a lot of work that needs to be done here, but I'm unsure of when it should be done and how it should be done.  I will open a PR soon that displays recurring events in the month, monthwidget, listing and instance views.

However, the database schema for recurring events needs a lot of work.  The current schema is this:

<table >
<tr>
<td>Field</td>
<td>Type</td>
<td>Null</td>
<td>Key</td>
<td>Default</td>
<td>Extra</td>
</tr>
<tr>
<td>id</td>
<td>int(10) unsigned</td>
<td>NO</td>
<td>PRI</td>
<td>NULL</td>
<td>auto_increment</td>
</tr>
<tr>
<td>recurringdate</td>
<td>date</td>
<td>NO</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>event_id</td>
<td>int(10) unsigned</td>
<td>NO</td>
<td>MUL</td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>recurrence_id</td>
<td>int(10) unsigned</td>
<td>NO</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>ongoing</td>
<td>tinyint(1)</td>
<td>YES</td>
<td></td>
<td>NULL</td>
<td></td>
</tr>
<tr>
<td>unlinked</td>
<td>tinyint(1)</td>
<td>YES</td>
<td>MUL</td>
<td>0</td>
<td></td>
</tr>
</table>

As you can see, a `recurringdate` record does not relate back to an `eventdatetime` record.  Instead it relates to a specific `event`.  Furthermore, because `recurringdate` only keeps track of the date, not the date and time, location, etc, it needs an existing `eventdatetime` for an `event`.  Because there is no direct fk relationship between `recurringdate` and `eventdatetime`, we have to assume that there will only ever be one `eventdatetime` for an `event` that has a `recurringdate` set.

The manager UI reflects this.  Once you add a recurring date to an event, you can not add any more eventdatetimes to that event.  The issue is that you can add a `recurringdate` if an event already has non-recurring `eventdatetimes`.  There is at least 1 event in the system with this problem, witch I found with the following SQL:

```
SELECT event_id, count(*) as total_recurring, (
    select count(*)
    FROM eventdatetime as e2
    WHERE e2.event_id = e.event_id
  ) as total_eventdattime
FROM eventdatetime as e
WHERE 
  e.recurringtype IS NOT NULL 
  AND e.recurringtype != 'none'
group by e.event_id
```

It would be much better to have `recurringdate` reference an `eventdatetime` record, rather than an `event` record.  That way the data is consistent, queries could be optimized easier, we could have multiple recurring dates for the same event, and we would no longer have erronious data (which result in phantom events).

However, this isn't a task for the frontend, but rather the backend and manager.
